version: '3.2'
services:
  db:
    image: mariadb:10.2.14
    restart: always
    ports:
      - "3306"
    networks:
      - sql-dev
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./containers/mysql/initdb.d/:/docker-entrypoint-initdb.d/"
      - "mysqldb:/var/lib/mysql"

  wordpress:
    image: $npm_package_name:latest
    environment:
      WP_ENV: development
      DB_HOST: db:3306
    depends_on:
      - db
    networks:
      - sql-dev
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./uploads-dev:/var/www/html/web/app/uploads:cached"
      - "./themes/$npm_package_config_themeSlug:/var/www/html/web/app/themes/$npm_package_config_themeSlug:cached" # the theme
      # - "./mu-plugins/my-custom-plugin:/var/www/html/web/app/mu-plugins/my-custom-plugin:cached" # custom plugin example

volumes:
  mysqldb:
networks:
  sql-dev:
    driver: bridge
